### ISSUE TITLE
Vagrant images are not stable

### ISSUE THREAD

**Issue by silentnights** [CESNET/Netopeer2GUI#20]
Hi,

I was trying to run Netopeer2GUI via the vagrant images, and I came with different issues depending on the image I am running.

OpenSUSE image currently does not work because of an incompatible swig version that is needed by libyang.
I tried to use a newer OpenSUSE version, but faced many missing dependencies which I resolved at the end and the GUI runs, but the backend always crash.

The Ubuntu image worked out of the box, but once I enter the server information, I realize I do not get any valid response from the server, later I realized that the frontend is working but the backend crashes.

I spent a long time trying to figure out what is going on, but at the end my guess is since the vagrant images uses the latest versions for all the dependencies from github, this might not be very stable as the code base changes for every user.

Would it be useful to get a vagrant image with specific known commits for the dependencies so that we can have a stable image?

I also tried the ubuntu release but again the backend was crashing whenever I try to connect to a netconf server.

**Comment by senderic** [comment]
That's the issue I am facing now myself. I am doing `git clone` command followed by a `git checkout abcdef01234` for the specific hash I am wanting. Good luck

**Comment by jakubman1** [comment]
Hello, the current vagrantfile is no longer valid, since some libraries made breaking changes. We are working on an updated version as well as dockerfile. Both should be available in February.
