### ISSUE TITLE
Single Device UI

### ISSUE THREAD

**Issue by jgroom33** [CESNET/Netopeer2GUI#7]
Current behavior:
liberouter can connect to multiple netconf servers

Desired behavior:
provide a set of environment variable that allow liberouter to connect to only 1 netconf device.
This behavior would eliminate user admin and the associated views

Use case:
Install and package liberouter directly on a netconf server to present a native UI for modify the 'localhost' server via a web interface.

Environment variables (or other implementation) could be defined as:
single_device <boolean>
single_device_username <string>
single_device_IP <string>
single_device_password <string>

**Comment by rkrejci** [comment]
I don't see a good reason to limit functionality of the interface.

On the other hand, the planned features is "an automatic connection to a specific NETCONF device" which could fullfill your needs. You could deploy NetopeerGUI with the predefined device which would be also set to be automatically connected whenever user login to the NetopeerGUI. But the user will be still able to connect to any other NETCONF device.

Would this be fine for you?

**Comment by jgroom33** [comment]
@rkrejci that feature sounds like it would help.

We're evaluating this project as a means to place a UI directly on a networking device. There are several devices in the Ciena portfolio that would be candidates for this implementation.

This implementation would provide a technician that needs to troubleshoot the device with an embedded mechanism to perform that goal.

**Comment by rkrejci** [comment]
Please try the current code.

When creating device in inventory, there is `autoconnect` checkbox to make the device automatically connected when user login and there is no connection to this device.

For your needs, it should be still the same - you are supposed to deploy gui with the backend's device list (`devices.json`). The only difference should be that the device described in this file should now have autoconnect enabled.
